/*
 * ELIMINACIÓN DE BASE DE DATOS
 */
-- DROP DATABASE `example`; --
/*
 * CREACIÓN DE BASE DE DATOS
 */
CREATE DATABASE `example` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
/*
 * CREACIÓN DE USUARIO 
 */
GRANT ALL ON example.* TO 'example'@'localhost' IDENTIFIED BY '12345678';
/*
 * RECARGAR PERMISOS EN EL MOTOR DE BDD
 */
FLUSH PRIVILEGES;

